# Generated by Django 5.2.15 on 2026-06-17 07:40
from django.conf import settings
from django.db import migrations, models


def add_user_field_and_populate(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    
    # Get the first user or create one if none exists
    default_user, created = User.objects.get_or_create(
        username='default_user',
        defaults={
            'email': 'default@example.com',
            'is_active': True,
        }
    )
    
    # Assign all existing tasks to this user
    Task.objects.update(user=default_user)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(add_user_field_and_populate, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
